# Site settings
title: "William\ R\.\ Blevins"
description: "This is my website. I think the URL is pretty self-explanatory." 
baseurl: "" 
url: "http://williamrblevins.info/:4000"
twitter_username: willblev
github_username:  willblev

markdown: kramdown
